### PR TITLE
New authenticator controller

### PR DESCRIPTION
**Pull request by asbiin**
The Authenticator class is good, but is not very flexible.
This PR splits the Authenticator in 2 classes :
- AuthenticatorController, used by Middleware to handle login request
- Authenticator, which does not depend on the current request, and can be used manually.

Authenticator come with 3 new public functions :
- IsActivated : true if current user has activated 2fa (2fa should be activated/deactivated on demand)
- login : to force login when verification has been made manually in the application (old storeAuthPassed function)
- verifyGoogle2FA($secret, $one_time_password) : to check secret an OTP manually

canPassWithoutCheckingOTP checks if user has activated 2FA (if not, it lets pass without 2FA)

### CODE REVIEW

**Comment by Thijmen** [comment]
I'd love to enable 2FA (secret key is not null) or disable 2FA (secret key is null). Is this PR what it's intent to do? @asbiin

**Comment by asbiin** [comment]
@Thijmen Yes that's exactly what this PR is intent to.
I have 1 page to enable 2fa, with a one_time_password input to verify if the user has correclty set its device. Until the 2fa challenge has passed, it's not activated yet. Disabling is the same: user has to enter one time password again to deactivate 2fa.

**Comment by asbiin** [comment]
@antonioribeiro What do you think of this ?

**Comment by antonioribeiro** [comment]
It's merged, thank you.

I've made some changes. The "Controller" name, could not really be used this way, so I just created a Google2FA class, extending the original Google2FA, and am instantiating it to be used as the Facade. So now this should work fine out of the box:

```
Google2FA::isActivated()
```

Could you please do some test on the master branch, please?

**Comment by asbiin** [comment]
@antonioribeiro I confirm it's OK with my application, all tests passes.

**Comment by antonioribeiro** [comment]
Version 0.2.0 tagged with this and more.

**Pull request merged**
