### PR TITLE
Change access level to public to fix PHP7.4 error

### PR DESCRIPTION
**Pull request by CyrilMazur**
Fixes https://github.com/antonioribeiro/google2fa-laravel/issues/96

### CODE REVIEW

**Comment by CyrilMazur** [comment]
@antonioribeiro can you check this PR? Your package throws an error on php 7.4. This PR fixes it.

**Comment by smartens80** [comment]
This PR being merged?

**Comment by ItsANameToo** [comment]
@antonioribeiro would be very much appreciated if this could get merged 😬

**Comment by smartens80** [comment]
@antonioribeiro can you merge? Would be greatly appreciated

**Comment by antonioribeiro** [comment]
Sorry guys, merged.

**Comment by antonioribeiro** [comment]
And tagged a new release

**Comment by smartens80** [comment]
@antonioribeiro you're a champ mate! Thank you

**Pull request merged**
