### PR TITLE
Add explicit support for Laravel 8

### PR DESCRIPTION
**Pull request by mfn**
## Summary
- Add Support for Laravel 8 (composer version)
- Adapt changed signature of `resolveRouteBinding`
- Improve travis testing matrix to _actually_ test against specific Laravel versions
- composer: all dev dependencies to be installed but prefer stable

### CODE REVIEW

**Comment by mfn** [comment]
Hmm, yeah. As I already thought, the travis matrix doesn't really test against individual Laravel versions, so only the latest stable was always tested.

Now that I added a temporary commit to only use Laravel 8, it won't install due to violation of minimum-stability in composer.

**Comment by mfn** [comment]
I've updated the travis matrix to test against actual Laravel versions (doesn't magically make Laravel 8 work though).

Let's wait until the release next week and then we'll re-trigger the jobs and see how it works

**Comment by mfn** [comment]
Hah, found it: added minimum-stability=dev but prefer-stable=true, which means we can now already test against L8 and it's all ✅

**Comment by mfn** [comment]
ping @antonioribeiro , thanks!

**Comment by mfn** [comment]
ping @antonioribeiro 🙏

**Comment by antonioribeiro** [comment]
Sorry for the delay. Just tagged a new version.

Thank you!

**Pull request merged**
