### PR TITLE
Allow usage of google2FA in stateless APIs

### PR DESCRIPTION
**Pull request by h44z**
For stateless APIs use as follows:

$authenticator = app(Authenticator::class)->boot**Api**($request);
if ($authenticator->isAuthenticated()) {
    // otp auth success....
}

### CODE REVIEW

**Comment by Shandur** [comment]
@antonioribeiro can you please update main package with this PR? It's really useful! I have the same problem with stateful thing.

**Comment by vrajroham** [comment]
+1

**Comment by zek** [comment]
+1

**Comment by antonioribeiro** [comment]
Merged. Thank you!

**Comment by antonioribeiro** [comment]
@h44z, we need some more tests, like passing authentication, are you able to write them?

**Comment by Shandur** [comment]
@antonioribeiro I've been using his PR for a few months and it works perfectly.
But if you need any tests, maybe I can help you with.
Authentication tests should be similar to authentication tests from your original package, right?

**Pull request merged**
